/*
Batch 80
Naman Jain 2014A7PS100P
Saksham Nagar 2014A7PS040P
*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
int flagp=0, flagp2=0; //for error printing
#include "lexerDef.h"
#include "parserDef.h"
#include "lexer.c"
#include "parser.c"
#include "SymTable.c"
#include "AST.c"
#include "codegen.c"
#include "typeChecker.c"



void comments(FILE* fp)
{
	fseek(fp, 0, SEEK_SET);
	while (fread(buffer, sizeof(char), (size_t)BUFFER_SIZE, fp))
		printf("%s", buffer);

		fseek(fp, 0, SEEK_SET);
}

void tklist(tokenInfo tk)
{
	while (tk !=NULL && tk->next != NULL)
	{
		printf("%s %s %d \n", tk->lexeme,IDtoStr(tk->token),  tk->lineno);
		tk=tk->next;
	}
}

void createListoftokens(FILE* fp, tokenInfo tokenList)
{
	while(fp != NULL)
	{
		fp = getStream(fp);
		if (fp==NULL) break;
		createLinkedList(tokenList);
	}
	while (tokenList !=NULL && tokenList->next != NULL)
	{
		tokenList=tokenList->next;
	}
	tokenInfo new=(tokenInfo) malloc (sizeof(struct tinfo));
	new->next=NULL;
	strcpy(new->lexeme,"$");
	new->token= $;
	tokenList->next=new;

}

int main(int argc, char ** argv)
{
	printf("LEVEL 4: Symbol table/AST/Type Checking/Semantic Analysis modules work.\n\n");
	int din;
	printf("Press option for the defined task.\n");
	printf("1. For printing the token list generated by the lexer.\n");
	printf("2. For parsing to verify the syntactic correctness of the input source code and to produce parse tree in inorder traversal (On Console)\n");
	printf("3. For printing the Abstract Syntax Tree in preorder traversal. (On Console)\n");
	printf("4. For displaying the amount of allocated memory and number of nodes to each of parse tree and abstract syntax tree for the test case used. \n");
	printf("5. For printing the Symbol Table and showing all relevant information.\n");
	printf("6. For compiling to verify the syntactic and semantic correctness of the input source code\n");
	printf("7. For producing assembly code\nOption? ");
	printf("\n");

	tokenInfo tokenList ,head;
	tokenList=(tokenInfo) malloc (sizeof(struct tinfo));
	tokenList->next= NULL;
	FILE* fp;
	FILE* fcl;

	char * origfile= argv[1];
	fp=removeComments(origfile, "cleanfile.txt");
	fcl=fp;

	fseek(fp, 0, SEEK_SET);
	populateHashTable();


	scanf("%d",&din);
	if(din==1)
	{
		flagp=0;
		createListoftokens(fp,tokenList);
		tokenList=tokenList->next;
		tklist(tokenList);

	}
	else if(din==2)
	{
		flagp=0;
		createListoftokens(fp,tokenList);
		tokenList=tokenList->next;
		populateGrammar();
		firstAndFollowSets();
		parseTable t;
		createParseTable(t);
		parseTree rut;
		rut= parseInputSourceCode(tokenList, t);
		if(rut->symbol==program)
		{
			printParseTreeConsole(rut);
		}
		else
		{
			printf("Syntactical errors occur in your code. Choose the particular option to view those errors.\n");

		}


	}
	else if(din==3)
	{
		flagp=0;
		createListoftokens(fp,tokenList);
		tokenList=tokenList->next;
		populateGrammar();
		firstAndFollowSets();
		parseTable t;
		createParseTable(t);
		parseTree rut;
		rut= parseInputSourceCode(tokenList, t);
		if(rut->symbol==program)
		{
			createAST(rut);
			collapseLinearChains(rut);
			collapseRepeatedRecursion(rut);
			printParseTreeConsole(rut);
		}
		else
		{
			printf("Syntactical errors occur in your code. Choose the particular option to view those errors.\n");

		}
	}
	else if(din==4)
	{
		flagp=0;
		createListoftokens(fp,tokenList);
		tokenList=tokenList->next;
		populateGrammar();
		firstAndFollowSets();
		parseTable t;
		createParseTable(t);
		parseTree rut;
		rut= parseInputSourceCode(tokenList, t);
		if(rut->symbol==program)
		{
			countnoparse(rut);
			createAST(rut);
			collapseLinearChains(rut);
			collapseRepeatedRecursion(rut);
			countnoast(rut);
			int n10=parsecount*sizeof(struct parsetree);
			int n11=astcount*sizeof(struct parsetree);
			printf("Parse Tree:\tNumber of nodes = %d Allocated memory = %d \n",parsecount, n10);
			printf("AST Tree:\tNumber of nodes = %d Allocated memory = %d \n",astcount,n11);
			printf("Compression percentage = ((%d-%d)/%d)*100 = %f\n",n10, n11,n10,((double)((n10-n11)/(double)n10)*100));

		}
		else
		{
			printf("Syntactical errors occur in your code. Choose the particular option to view those errors.\n");

		}
		
	}
	else if(din==5)
	{
		flagp=0;
		createListoftokens(fp,tokenList);
		tokenList=tokenList->next;
		populateGrammar();
		firstAndFollowSets();
		parseTable t;
		createParseTable(t);
		parseTree rut;
		rut= parseInputSourceCode(tokenList, t);
		if(rut->symbol==program)
		{
			populateSymTable(rut);
			printSymTable();

		}
		else
		{
			printf("Syntactical errors occur in your code. Choose the particular option to view those errors.\n");

		}
	}
	else if(din==6)
	{
		flagp=1;
		createListoftokens(fp,tokenList);
		tokenList=tokenList->next;
		populateGrammar();
		firstAndFollowSets();
		parseTable t;
		createParseTable(t);
		parseTree rut;
		rut= parseInputSourceCode(tokenList, t);
		if(rut->symbol==program)
		{
			populateSymTable(rut);
			createAST(rut);
			semanticAnalyze(rut);
			checkRetVal();
			typeCheck(rut);
			if(flagp2==0)
				printf("Code compiles sucessfully...\n");

		}
		else
		{
			printf("Syntactical errors occur in your code. Resolve them to view the other semantic, typecheck errors.\n");

		}
	}
	else if(din==7)
	{
		flagp=0;
		createListoftokens(fp,tokenList);
		tokenList=tokenList->next;
		populateGrammar();
		firstAndFollowSets();
		parseTable t;
		createParseTable(t);
		parseTree rut;
		rut= parseInputSourceCode(tokenList, t);
		if(rut->symbol==program)
		{
			populateSymTable(rut);
			createAST(rut);
			semanticAnalyze(rut);
			checkRetVal();
			typeCheck(rut);
			if(flagp2)
				printf("Code cannot be generated, errors occur in your code\n");
			else
			{
				printf("Code compiles successfully...\n");
				codegen(rut, argv[2]);
				printf("Code generated, check output file\n");
			}
		}
		else
		{
			printf("Syntactical errors occur in your code. Resolve them to view the other semantic, typecheck errors.\n");

		}
		
	}

	return 0;
}


